on:
  workflow_call:
    secrets:
      ASANA_CONNECT_TOKEN:
        required: true

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:
      - name: Create a comment
        uses: Asana/comment-on-task-github-action@latest
        id: createComment
        with:
          asana-secret: ${{ secrets.ASANA_CONNECT_TOKEN }}
          comment-text: "{{PR_NAME}} is {{PR_STATE}}: {{PR_URL}}"
      - name: Log status
        run: echo "Status is ${{ steps.createComment.outputs.status }}"
