on:
  workflow_call:
    secrets:
      ASANA_CONNECT_TOKEN:
        required: true

jobs:
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    name: Create pull request attachments on Asana tasks
    steps:
      - name: Create pull request attachments
        uses: Asana/create-app-attachment-github-action@latest
        id: postAttachment
        with:
          asana-secret: ${{ secrets.ASANA_CONNECT_TOKEN }}
      - name: Log output status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
